services:
 nginx-proxy:
  image: 'jc21/nginx-proxy-manager:latest'
  container_name: nginx-proxy
  hostname: nginx-proxy
  restart: always
  volumes:
   - ./data:/data
   - ./letsencrypt:/etc/letsencrypt
  ports:
   - '80:80'
   - '81:81'
   - '443:443'

 mail:
  image: docker.io/mailserver/docker-mailserver:edge
  container_name: mail-server
  hostname: mail
  domainname: write_your_value
  ports:
   - "25":"25"
   - "465:465"
   - "993:993"
  restart: always
  volumes:
   - ./letsencrypt:/etc/letsencrypt
  environment:
   - SSL_TYPE=manual
   - SSL_CERT_PATH=/etc/letsencrypt/live/npm-X/fullchain.pem
   - SSL_KEY_PATH=/etc/letsencrypt/live/npm-X/privkey.pem
   - TLS_LEVEL=modern
   - ENABLE_SPAMASSASSIN=1
   - SPAMASSASSIN_SPAM_TO_INBOX=1
   - ENABLE_CLAMAV=1
   - ENABLE_FAIL2BAN=1
   - ENABLE_POSTGREY=1
   - ENABLE_SASLAUTHD=0
   - ONE_DIR=1
  cap_add:
   - NET_ADMIN
   - SYS_PTRACE
  
